src/index.js
src/redux/auth/auth.operations.js
src/redux/auth/auth.selectors.js
src/redux/auth/auth.slice.js
src/redux/store.js

redux-auth-register

---

src/components/CalendarTable/CalendarTable.jsx
src/components/CalendarTable/CalendarTable.module.css

Есть идеи как сделать чтобы вправо вьехал  календарь (буду потихоньку фунционал добавлять)

fix styles but not all of them

---

src/components/App.jsx
src/components/CalendarTable/CalendarTable.jsx
src/components/CalendarTable/CalendarTable.module.css
src/pages/Calendar/Calendar.js

Мне нужен код ревью, потому что есть ощущение что там очень много костылей

Calendar style

---

src/components/App.jsx
src/components/CalendarTable/CalendarTable.module.css
src/components/Header/Header.jsx
src/components/Header/Header.module.css
src/components/LoginForm/LoginForm.jsx
src/components/MainLayout/MainLayout.js
src/components/MainLayout/MainLayout.module.css
src/components/RestrictedRoute.jsx
src/components/UserInfo/UserInfo.jsx
src/hooks/useAuth.js
src/pages/Account/Account.module.css

- зробив редірект з login/register на головну сторінку
- зробив відображення ім'я в Header
- корекція головної сторінки
ElenaOds Бачив, що переді мною ще є пул. Можу обновитися коли його приймеш, щоб ти не виправляла конфлікти.

fix header/app

---

src/components/App.jsx
src/components/RegisterForm/RegisterForm.js
src/components/RegisterForm/RegisterForm.module.css
src/pages/Login/Login.jsx
src/pages/Register/Register.js
src/redux/auth/auth.operations.js
src/redux/auth/auth.slice.js
src/services/todoAPI/authAPI.js

refreshUser

---

src/components/App.jsx
src/components/AuthRouts/PrivateRoute.jsx
src/components/AuthRouts/PublicRoute.jsx
src/components/RestrictedRoute.jsx
src/pages/Home/Home.js

Private and Public Routes

---

src/components/TestTasksRequests/TestTasksRequests.jsx
src/redux/tasks/tasks.operations.js
src/services/gooseTrackAPI.js

all task requests are working

---

src/components/PeriodTypeSelect/PeriodTypeSelect.js
src/components/PeriodTypeSelect/PeriodTypeSelect.module.css

Додаті стилі для кнопок Month Day
позиціювання,hover,active

PeriodTypeSelect

---

src/components/CalendarTable/CalendarTable.jsx
src/components/CalendarTable/CalendarTable.module.css
src/pages/Calendar/Calendar.js

я сделал таски теперь они отображаются, я рад))

FInishTask)))

---

src/components/ChosenDay/ChosenDay.js
src/components/ChosenDay/ChosenDay.module.css
src/components/DayCalendarHead/DayCalendarHead.jsx
src/components/DayCalendarHead/DayCalendarHead.module.css
src/components/TasksColumnsList/TasksColumnsList.jsx
src/components/TasksColumnsList/TasksColumnsList.module.css
src/icons/addIcon.svg

done choosen day

---

src/components/App.jsx
src/pages/Calendar/Calendar.js

it's not perfect. does not solve the problem with reloading page and staying on the same date. For now we can work with it

Fix route calendar

---

src/components/App.jsx
src/components/CalendarToolbar/CalendarToolbar.jsx
src/components/ChosenMonth/ChosenMonth.js
src/components/PeriodPaginator/PeriodPaginator.jsx
src/pages/Calendar/Calendar.js

Я там перевернул весь код с месяцем пагинация теперь работает, с днем посмотрю ближе к ночи мне бежать надо

работает теперь месяц пагинатор

---

src/components/TestTasksRequests/TestTasksRequests.jsx
src/redux/store.js
src/redux/user/user.operations.js
src/redux/user/user.slice.js

validation from back end has to be clear for front end. I had difficulties with updating phone number and birthday

slice is ready, requests is working

---

src/components/PeriodPaginator/PeriodPaginator.jsx
src/pages/Calendar/Calendar.js

Надо чтобы кто то закинул в локалсторадж const [state, setState] = useState({
isActivePage: false,
currentDate: new Date(),
month: 0
}); потому что перезагрузке страницы там ад происхоидт и при переходе на страницы, мне надо отойти на какое то время, мб может кто то взяться

Работает но

---

src/hooks/useDate.js

якщо дата в форматі ddMMMMyyyy то цей хук витягує поточну дату з url

created useDate - to get date from url

---

src/components/ChosenDay/ChosenDay.js
src/components/ChosenMonth/ChosenMonth.js
src/components/PeriodPaginator/PeriodPaginator.jsx
src/components/UserInfo/ModalUserInfo/ModalUserInfo.jsx
src/pages/Home/Home.jsx

Add style day

---

src/components/TaskColumnCard/TaskColumnCard.module.css
src/components/TaskToolbar/Move/Modal.jsx
src/components/TaskToolbar/Move/Modal.module.css
src/components/TaskToolbar/TaskToolbar.module.css

smoll fix but move not working

smoll fix taskToolbar

---

src/components/App.jsx
src/components/PageNotFound/PageNotFound.jsx
src/components/PageNotFound/PageNotFound.module.css

Компонент 404 зробив
через 2 години ще займусь стилізацією
Роути якщо не авторизован ведуть на мейн
якщо авторизован на календар

404 ошибка

---

src/components/TaskToolbar/Move/Modal.jsx

move is working but after update

taskToolbar

---

src/components/TaskToolbar/Delete/Delete.jsx
src/components/TaskToolbar/Move/Modal.jsx

correct render tasks cards

---

src/components/CalendarTable/CalendarTable.jsx
src/components/ChosenMonth/ChosenMonth.js

тепер в таблиці місяця рендерятьс тільки таски на вибраний місяць

fixed fetch tasks for each month

---

public/index.html
src/components/UserInfo/ModalUser/ModalUser.jsx
src/components/UserInfo/ModalUserInfo/ModalUserInfo.module.css
src/components/UserInfo/UserInfo.jsx

userModal window over all windows with createPortal

fix userModalwindow

---

src/components/ChosenDay/ChosenDay.js
src/pages/Calendar/Calendar.js

Зробив, щоб грузизиль такски на кожен день, але треба перевірити, так як робив поспіхом

fixed request

---

src/components/CalendarTable/CalendarTable.jsx
src/components/CalendarTable/CalendarTable.module.css

Разобрался с подсветкой активного дня
правильное позиционирование активного дня будет готово завтра
бо надо еще время

Подсвечивание дня ндеели

---

src/components/CalendarTable/CalendarTable.jsx
src/components/CalendarTable/CalendarTable.module.css
src/index.css

Styles for tasks in calendar

---

src/components/CalendarTable/CalendarTable.jsx
src/components/CalendarTable/CalendarTable.module.css

fix semantik

---

src/components/CalendarTable/CalendarTable.jsx
src/components/CalendarTable/CalendarTable.module.css
src/components/MonthCalendarHead/MonthCalendarHead.js
src/components/MonthCalendarHead/MonthCalendarHead.module.css

дні другого місяця тепер іншого кольору

Calendar table fix

---

src/components/PeriodTypeSelect/PeriodTypeSelect.js

при переключенні з місяця на день, іде перевірка, якщо поточна дата знаходиться в данному місяці, то переходить на сьогоднішню дату, але якщо ми в іншому місяці, то перехід буде на 1ше число вибраного місяця

day-month switch gets to today on Day section
